# fly.toml app configuration file generated for bhartiya on 2023-05-03T14:44:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bhartiya"
app_name = "bhartiya"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]